import type * as SQLite from 'expo-sqlite';
import { EquipmentType, LoadType, MuscleGroup } from '../constants/enums';
import type { Exercise, NutritionMetric } from '../types/schema';
import { getDb } from './db';

type SeedDb = Pick<SQLite.SQLiteDatabase, 'getFirstAsync' | 'runAsync'>;

type SeedExercise = Pick<
  Exercise,
  | 'id'
  | 'name'
  | 'category'
  | 'setMode'
  | 'loadType'
  | 'muscleGroupsPrimary'
  | 'muscleGroupsSecondary'
> & {
  equipment: EquipmentType;
};

type SeedNutritionMetric = Pick<
  NutritionMetric,
  'id' | 'name' | 'unit' | 'displayOrder'
>;

const SEEDED_EXERCISES: readonly SeedExercise[] = [
  {
    id: 'seed-barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [
      MuscleGroup.HAMSTRINGS,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-barbell-front-squat',
    name: 'Barbell Front Squat',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS],
    muscleGroupsSecondary: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-goblet-squat',
    name: 'Goblet Squat',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.CORE],
    equipment: EquipmentType.KETTLEBELL,
  },
  {
    id: 'seed-leg-press',
    name: 'Leg Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.HAMSTRINGS],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-leg-extension',
    name: 'Leg Extension',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-walking-lunge',
    name: 'Walking Lunge',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [
      MuscleGroup.HAMSTRINGS,
      MuscleGroup.CALVES,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [
      MuscleGroup.HAMSTRINGS,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-step-up',
    name: 'Step-Up',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.HAMSTRINGS, MuscleGroup.CALVES],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-wall-sit',
    name: 'Wall Sit',
    category: 'workout',
    setMode: 'duration',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.QUADS],
    muscleGroupsSecondary: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-conventional-deadlift',
    name: 'Conventional Deadlift',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [
      MuscleGroup.HAMSTRINGS,
      MuscleGroup.GLUTES,
      MuscleGroup.BACK,
    ],
    muscleGroupsSecondary: [
      MuscleGroup.QUADS,
      MuscleGroup.FOREARMS,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.BACK, MuscleGroup.FOREARMS],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-good-morning',
    name: 'Good Morning',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.BACK, MuscleGroup.CORE],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-lying-leg-curl',
    name: 'Lying Leg Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.HAMSTRINGS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-seated-leg-curl',
    name: 'Seated Leg Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.HAMSTRINGS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-glute-ham-raise',
    name: 'Glute-Ham Raise',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.CALVES, MuscleGroup.CORE],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-glute-bridge',
    name: 'Glute Bridge',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.GLUTES],
    muscleGroupsSecondary: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-cable-pull-through',
    name: 'Cable Pull Through',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    muscleGroupsSecondary: [MuscleGroup.BACK],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    muscleGroupsSecondary: [
      MuscleGroup.BACK,
      MuscleGroup.CORE,
      MuscleGroup.SHOULDERS,
    ],
    equipment: EquipmentType.KETTLEBELL,
  },
  {
    id: 'seed-standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CALVES],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CALVES],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-tibialis-raise',
    name: 'Tibialis Raise',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.CALVES],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-flat-barbell-bench-press',
    name: 'Flat Barbell Bench Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-flat-dumbbell-bench-press',
    name: 'Flat Dumbbell Bench Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-incline-dumbbell-bench-press',
    name: 'Incline Dumbbell Bench Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-dumbbell-fly',
    name: 'Dumbbell Fly',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-cable-fly',
    name: 'Cable Fly',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-push-up',
    name: 'Push-Up',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.CHEST],
    muscleGroupsSecondary: [
      MuscleGroup.TRICEPS,
      MuscleGroup.SHOULDERS,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-dips',
    name: 'Dips',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS, MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-assisted-dip',
    name: 'Assisted Dip',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.ASSISTED,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS, MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-barbell-overhead-press',
    name: 'Barbell Overhead Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-arnold-press',
    name: 'Arnold Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-lateral-raise',
    name: 'Lateral Raise',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-rear-delt-fly',
    name: 'Rear Delt Fly',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS],
    muscleGroupsSecondary: [MuscleGroup.BACK],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-face-pull',
    name: 'Face Pull',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-landmine-press',
    name: 'Landmine Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS, MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.BANDS,
  },
  {
    id: 'seed-pull-up',
    name: 'Pull-Up',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-assisted-pull-up',
    name: 'Assisted Pull-Up',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.ASSISTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-chin-up',
    name: 'Chin-Up',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.BACK, MuscleGroup.BICEPS],
    muscleGroupsSecondary: [MuscleGroup.FOREARMS],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-lat-pulldown',
    name: 'Lat Pulldown',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-barbell-row',
    name: 'Barbell Row',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [
      MuscleGroup.BICEPS,
      MuscleGroup.FOREARMS,
      MuscleGroup.HAMSTRINGS,
    ],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-one-arm-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-seated-cable-row',
    name: 'Seated Cable Row',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-chest-supported-row',
    name: 'Chest-Supported Row',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.BICEPS],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-inverted-row',
    name: 'Inverted Row',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.BACK],
    muscleGroupsSecondary: [
      MuscleGroup.BICEPS,
      MuscleGroup.FOREARMS,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-barbell-curl',
    name: 'Barbell Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BICEPS],
    muscleGroupsSecondary: [MuscleGroup.FOREARMS],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BICEPS],
    muscleGroupsSecondary: [MuscleGroup.FOREARMS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-hammer-curl',
    name: 'Hammer Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BICEPS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-preacher-curl',
    name: 'Preacher Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.BICEPS],
    muscleGroupsSecondary: [MuscleGroup.FOREARMS],
    equipment: EquipmentType.MACHINE,
  },
  {
    id: 'seed-tricep-pushdown',
    name: 'Tricep Pushdown',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-skull-crusher',
    name: 'Skull Crusher',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS, MuscleGroup.CHEST],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-dumbbell-tricep-kickback',
    name: 'Dumbbell Tricep Kickback',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.TRICEPS],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-wrist-curl',
    name: 'Wrist Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FOREARMS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FOREARMS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-reverse-curl',
    name: 'Reverse Curl',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FOREARMS, MuscleGroup.BICEPS],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-farmer-carry',
    name: 'Farmer Carry',
    category: 'workout',
    setMode: 'duration',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FOREARMS, MuscleGroup.FULL_BODY],
    muscleGroupsSecondary: [
      MuscleGroup.CORE,
      MuscleGroup.SHOULDERS,
      MuscleGroup.CALVES,
    ],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-dead-hang',
    name: 'Dead Hang',
    category: 'workout',
    setMode: 'duration',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.FOREARMS, MuscleGroup.BACK],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-plank',
    name: 'Plank',
    category: 'workout',
    setMode: 'duration',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS, MuscleGroup.GLUTES],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-side-plank',
    name: 'Side Plank',
    category: 'workout',
    setMode: 'duration',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS, MuscleGroup.GLUTES],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-hanging-knee-raise',
    name: 'Hanging Knee Raise',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [MuscleGroup.FOREARMS],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-cable-crunch',
    name: 'Cable Crunch',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-russian-twist',
    name: 'Russian Twist',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-pallof-press',
    name: 'Pallof Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS],
    equipment: EquipmentType.CABLE,
  },
  {
    id: 'seed-ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.CORE],
    muscleGroupsSecondary: [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
    equipment: EquipmentType.OTHER,
  },
  {
    id: 'seed-burpee',
    name: 'Burpee',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.FULL_BODY],
    muscleGroupsSecondary: [
      MuscleGroup.CHEST,
      MuscleGroup.QUADS,
      MuscleGroup.SHOULDERS,
      MuscleGroup.CORE,
    ],
    equipment: EquipmentType.BODYWEIGHT,
  },
  {
    id: 'seed-turkish-get-up',
    name: 'Turkish Get-Up',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FULL_BODY],
    muscleGroupsSecondary: [
      MuscleGroup.SHOULDERS,
      MuscleGroup.CORE,
      MuscleGroup.GLUTES,
    ],
    equipment: EquipmentType.KETTLEBELL,
  },
  {
    id: 'seed-dumbbell-thruster',
    name: 'Dumbbell Thruster',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FULL_BODY],
    muscleGroupsSecondary: [
      MuscleGroup.QUADS,
      MuscleGroup.GLUTES,
      MuscleGroup.SHOULDERS,
      MuscleGroup.TRICEPS,
    ],
    equipment: EquipmentType.DUMBBELL,
  },
  {
    id: 'seed-clean-and-press',
    name: 'Clean and Press',
    category: 'workout',
    setMode: 'reps',
    loadType: LoadType.WEIGHTED,
    muscleGroupsPrimary: [MuscleGroup.FULL_BODY],
    muscleGroupsSecondary: [
      MuscleGroup.GLUTES,
      MuscleGroup.HAMSTRINGS,
      MuscleGroup.SHOULDERS,
      MuscleGroup.BACK,
    ],
    equipment: EquipmentType.BARBELL,
  },
  {
    id: 'seed-battle-rope-slams',
    name: 'Battle Rope Slams',
    category: 'workout',
    setMode: 'duration',
    loadType: LoadType.BODYWEIGHT,
    muscleGroupsPrimary: [MuscleGroup.FULL_BODY],
    muscleGroupsSecondary: [
      MuscleGroup.SHOULDERS,
      MuscleGroup.CORE,
      MuscleGroup.BACK,
    ],
    equipment: EquipmentType.OTHER,
  },
];

const SEEDED_NUTRITION_METRICS: readonly SeedNutritionMetric[] = [
  {
    id: 'seed-nutrition-calories',
    name: 'Calories',
    unit: 'kcal',
    displayOrder: 0,
  },
  {
    id: 'seed-nutrition-protein',
    name: 'Protein',
    unit: 'g',
    displayOrder: 1,
  },
  {
    id: 'seed-nutrition-carbs',
    name: 'Carbs',
    unit: 'g',
    displayOrder: 2,
  },
  {
    id: 'seed-nutrition-fat',
    name: 'Fat',
    unit: 'g',
    displayOrder: 3,
  },
  {
    id: 'seed-nutrition-fiber',
    name: 'Fiber',
    unit: 'g',
    displayOrder: 4,
  },
  {
    id: 'seed-nutrition-sugar',
    name: 'Sugar',
    unit: 'g',
    displayOrder: 5,
  },
  {
    id: 'seed-nutrition-sodium',
    name: 'Sodium',
    unit: 'mg',
    displayOrder: 6,
  },
  {
    id: 'seed-nutrition-saturated-fat',
    name: 'Saturated Fat',
    unit: 'g',
    displayOrder: 7,
  },
  {
    id: 'seed-nutrition-cholesterol',
    name: 'Cholesterol',
    unit: 'mg',
    displayOrder: 8,
  },
];

export async function seedBuiltInData(): Promise<void> {
  const db = getDb();

  await db.withExclusiveTransactionAsync(async (txn) => {
    for (const exercise of SEEDED_EXERCISES) {
      if (!(await exerciseExists(txn, exercise.id))) {
        await insertExercise(txn, exercise);
      }
    }

    for (const metric of SEEDED_NUTRITION_METRICS) {
      if (!(await nutritionMetricExists(txn, metric.id))) {
        await insertNutritionMetric(txn, metric);
      }
    }
  });
}

async function exerciseExists(db: SeedDb, exerciseId: string): Promise<boolean> {
  const row = await db.getFirstAsync<{ id: string }>(
    `SELECT id
    FROM Exercise
    WHERE id = ?
    LIMIT 1`,
    exerciseId
  );

  return Boolean(row);
}

async function nutritionMetricExists(
  db: SeedDb,
  metricId: string
): Promise<boolean> {
  const row = await db.getFirstAsync<{ id: string }>(
    `SELECT id
    FROM NutritionMetric
    WHERE id = ?
    LIMIT 1`,
    metricId
  );

  return Boolean(row);
}

async function insertExercise(
  db: SeedDb,
  exercise: SeedExercise
): Promise<void> {
  await db.runAsync(
    `INSERT INTO Exercise (
      id, userId, name, category, setMode, loadType,
      muscleGroupsPrimary, muscleGroupsSecondary, equipment
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    exercise.id,
    null,
    exercise.name,
    exercise.category,
    exercise.setMode,
    exercise.loadType,
    JSON.stringify(exercise.muscleGroupsPrimary),
    JSON.stringify(exercise.muscleGroupsSecondary),
    exercise.equipment
  );
}

async function insertNutritionMetric(
  db: SeedDb,
  metric: SeedNutritionMetric
): Promise<void> {
  await db.runAsync(
    `INSERT INTO NutritionMetric (
      id, userId, name, unit, isSeeded, displayOrder
    )
    VALUES (?, ?, ?, ?, ?, ?)`,
    metric.id,
    null,
    metric.name,
    metric.unit,
    1,
    metric.displayOrder
  );
}
